src/Services/SwaggerService.php
=> #49:- update description generating logic;

config/auto-doc.php, src/Services/SwaggerService.php
=> feat: change description of additional_paths

src/Exceptions/EmptyContactEmailException.php, src/Services/SwaggerService.php, src/Validators/SwaggerSpecValidator.php, tests/SwaggerServiceTest.php, tests/TestCase.php, tests/fixtures/PushDocumentationCommandTest/documentation.json, tests/fixtures/SwaggerServiceTest/tmp_data_request_with_empty_data_jwt.json, tests/fixtures/SwaggerServiceTest/tmp_data_request_with_empty_data_laravel.json
Mandatory field `info.contact.email` of `auto-doc.php` was incorrectly validated. It caused errors during the common usage of package.
Fixes #84
=> fix: incorrect path in config checking

src/Validators/SwaggerSpecValidator.php
`Date`, `double` and `object` were added to the primitive types array to cover cases when we convert validation rules to the new parameter type which is not primitive.
Fixes #104 (issue)
=> feat: extends primitive types by date, double, and object

src/Services/SwaggerService.php
Extend available content types for prepare response examples
=> fix: add image to available content types

src/Exceptions/DocFileNotExistsException.php, src/Exceptions/EmptyDocFileException.php, src/Services/SwaggerService.php, tests/AutoDocControllerTest.php
Added new exceptions for cases when external Open-API doc file (added via `auto-doc.additional_paths`) is not exists or empty (complitely empty or not in a JSOn format).
Fixes #45
=> Throw exception for empty or not exists files

composer.json, composer.lock, src/Services/SwaggerService.php, tests/AutoDocControllerTest.php
Catching and reporting exceptions during Open-API file validation and not crushing document building process.
Fixes # (45)
=> feat: catch and report exception during Open-Api file validation (#45)

readme.md
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
=> documentation: update readme.md

src/Exceptions/UnsupportedDocumentationViewerException.php, src/Services/SwaggerService.php, tests/SwaggerServiceTest.php
Add handling unsupported documentation viewer configuration. Throw the `UnsupportedDocumentationViewerException` exception if an invalid value was provided.
Fixes #93
=> feat: add exception for invalid documentation_viewer configuration.

readme.md, src/Services/SwaggerService.php, tests/fixtures/AutoDocMiddlewareTest/tmp_data_search_roles_request.json, tests/fixtures/SwaggerServiceTest/tmp_data_create_user_request.json, tests/fixtures/SwaggerServiceTest/tmp_data_get_user_request.json, tests/fixtures/SwaggerServiceTest/tmp_data_post_user_request.json, tests/fixtures/SwaggerServiceTest/tmp_data_post_user_request_with_object_params.json, tests/fixtures/SwaggerServiceTest/tmp_data_put_user_request.json, tests/fixtures/SwaggerServiceTest/tmp_data_put_user_request_with_early_generated_doc.json, tests/fixtures/SwaggerServiceTest/tmp_data_search_roles_request.json, tests/fixtures/SwaggerServiceTest/tmp_data_search_roles_request_invalid_content_type.json, tests/fixtures/SwaggerServiceTest/tmp_data_search_roles_request_jwt_security.json, tests/fixtures/SwaggerServiceTest/tmp_data_search_roles_request_laravel_security.json, tests/fixtures/SwaggerServiceTest/tmp_data_search_roles_request_pdf.json, tests/fixtures/SwaggerServiceTest/tmp_data_search_roles_request_plain_text.json, tests/fixtures/SwaggerServiceTest/tmp_data_search_roles_request_with_annotations.json, tests/fixtures/SwaggerServiceTest/tmp_data_search_roles_request_without_info.json, tests/fixtures/SwaggerServiceTest/tmp_data_search_roles_request_without_rule_type.json, tests/fixtures/SwaggerServiceTest/tmp_data_search_users_request.json, tests/support/Mock/TestRequestWithAnnotations.php
Add the ability to mark routes as deprecated.
Fixes #102
=> feat: add ability to mark routes as deprecated.

readme.md
Add a table with comparison criteria between LaravelSwagger and other documentation generators
=> docs: add documentation block with comparison to another generators

readme.md
Change text in comparison block
=> Correct comparison block.

src/Services/SwaggerService.php, tests/SwaggerServiceTest.php, tests/fixtures/SwaggerServiceTest/example_success_user_response.json, tests/fixtures/SwaggerServiceTest/tmp_data_get_user_request.json, tests/support/Traits/SwaggerServiceMockTrait.php
We have an issue when the response contains a field with the name `type`. Here is an example of response structure:
```json
{
"type": "object",
"properties": {
"id": {
"type": "integer"
},
"type": {
"type": "string"
},
"comment": {
"type": "string",
"nullable": true
},
"color_code": {
"nullable": true,
"type": "string"
}
}
}
```
When we are trying to [get the definition of the field](https://github.com/RonasIT/laravel-swagger/blob/master/src/Services/SwaggerService.php#L320) the following error occurs:
```bash
TypeError: Cannot access offset of type string on string in /app/vendor/ronasit/laravel-swagger/src/Services/SwaggerService.php:325
```
The reason is that the `Arr::get` takes the first occurrence on the `type` in the array, not the correct one.
=> Error when handling response with the field name "type"

src/Services/SwaggerService.php, tests/fixtures/SwaggerServiceTest/tmp_data_put_user_request_with_early_generated_doc.json
If the response contains no data (eg. delete or put) we ignore them and don't save the definition of such response into the `definitions` section of the `documentation.json` file. At the same time, the `paths.**.responses` section still contains names of such definitions. So it raises an exception during OpenAPI file validation.
=> fix: missed response definition when the content of response was empty

src/Tests/PhpUnitEventSubscribers/SwaggerSaveDocumentationSubscriber.php
The documentation generates only for the single test case. So the final `documentation.json` file contains information from the last test case. The reason is the incorrect event of PHPUnit. I changed `PHPUnit\Event\Test\AfterLastTestMethodFinished` to `PHPUnit\Event\Application\Finished` and as a result, a subscriber will run only when all tests finish.
=> fix: documentation creates only for the last test case

composer.json, composer.lock, docker-compose.yml, tests/SwaggerServiceTest.php
To update `laravel-empty-project` to Laravel 11 we need to add a support of Laravel 11 here.
Fixes # (issue)
=> chore: update dependencies

MIGRATION-GUIDES.md, config/auto-doc.php, phpunit.xml, readme.md, src/Contracts/SwaggerDriverContract.php, src/Drivers/BaseDriver.php, src/Services/SwaggerService.php, src/Support/PHPUnit/EventSubscribers/SwaggerSaveDocumentationSubscriber.php, src/Support/PHPUnit/Extensions/SwaggerExtension.php, src/Traits/AutoDocTestCaseTrait.php
Update outdated readme file, fix namespace for autodoc trait and phpunit extensions
=> doc: update readme, add migration guide

phpunit.xml
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
=> feat: ignore PHPUnit extensions classes from coverage

src/Services/SwaggerService.php, src/Traits/GetDependenciesTrait.php, tests/SwaggerServiceTest.php, tests/fixtures/SwaggerServiceTest/tmp_data_get_user_request_without_request_class.json
Hi, it refactors the `resolveClassMethodDependencies` method. Tests already cover these changes.
=> Refactoring resolveClassMethodDependencies method

.gitattributes, .gitignore
Create the `.gitattributes` file to prevent downloading useless test files by devs.
=> Add `.gitattributes` file
